"""Generated ``AGENTS.md`` for merve classifier repositories (RFC 0002 A1/A2).

``merve init`` scaffolds an ``AGENTS.md`` — the cross-tool agent-guidance
convention — into every new classifier repo, and ``merve init-agents``
regenerates it for existing ones. The content is *generated* from a template
shipped in merve (never hand-written), parameterized on the single/multi
config shape and the classifier names, and stamped with both the installed
merve version and a template version. Because it is generated and
version-stamped, it can be regenerated after upgrades and checked for
staleness by ``merve doctor`` — exactly like the CI workflow is.

Public API:

- ``AGENTS_MD_TEMPLATE_VERSION`` — the template version stamped into the file.
- ``generate_agents_md(...)`` — render the template to a string.
- ``parse_agents_md_version(path)`` — read the template-version stamp back.
- ``init_agents_md(project_path, force)`` — detect config shape and write the
  file (same return contract as ``init_github_actions``).
"""

import re
from pathlib import Path
from typing import Optional

# Bump on incompatible template changes (mirrors github_actions.py's workflow
# version). ``merve doctor`` warns when a file's stamp does not match this.
AGENTS_MD_TEMPLATE_VERSION = "1.0"

# The normative AGENTS.md body from RFC 0002 §4, verbatim. Lines prefixed with
# ``[SINGLE]`` render only for single-classifier repos; ``[MULTI]`` only for
# multi-classifier repos (the marker is stripped either way). ``{merve_version}``,
# ``{TEMPLATE_VERSION}``, ``{classifier_list}`` and ``{default_classifier}`` are
# substituted at render time. A raw string keeps the line-continuation backslash
# in the curl example literal and the ``{...}`` JSON snippets untouched.
_AGENTS_MD_TEMPLATE = r"""<!-- Generated by merve {merve_version}. Do not edit by hand;
     regenerate with: merve init-agents --force
     AGENTS.md template version: {TEMPLATE_VERSION} -->

# Operating this repository (for coding agents and humans)

This repository serves ML classifiers with [Merve](https://github.com/core64-lab/merve)
(`pip install merve`): Python predictor classes wrapped into a FastAPI inference
API, configured by `mlserver.yaml`. The CLI is `merve` (`mlserver` is a
deprecated alias). The importable Python module is still named `mlserver`, the
config file is `mlserver.yaml`, and env vars are `MLSERVER_*` — only the tool
is called merve; do not rename those.

## The 60-second tour

[SINGLE]- Config: `mlserver.yaml` (single classifier — one top-level `predictor:` section).
[SINGLE]- Serve locally: `merve serve`
[MULTI]- Config: `mlserver.yaml` (multi-classifier — top-level `classifiers:` section).
[MULTI]- Classifiers here: {classifier_list}. Default: {default_classifier}.
[MULTI]- Serve locally: `merve serve --classifier <name>`
- Every server process serves ONE classifier at flat paths: `POST /predict`,
  `POST /predict_proba`, `GET /info`, `GET /healthz`, `GET /status`,
  `GET /metrics` — no version or classifier name in URLs.
- Versions come from git tags only (`merve tag`), canonical format
  `<classifier>/vX.Y.Z`. `classifier.version` in the YAML is display-only.
- Validate any config change before serving: `merve validate --json`.

## Request shape (canonical)

Send input keys at the TOP LEVEL of the JSON body:

```bash
curl -X POST localhost:8000/predict -H 'Content-Type: application/json' \
  -d '{"records": [{"feature_a": 1.0, "feature_b": "x"}]}'
```

Accepted top-level keys: `records` / `instances` (list of feature dicts),
`features` (single feature dict), `ndarray` / `inputs` (nested arrays; require
`api.adapter: ndarray` or `auto`). The legacy `{"payload": {...}}` wrapper is
deprecated (removal targeted for 1.0) — do not write new code with it.

The running server documents itself: `GET /openapi.json` carries request
examples and response schemas; `GET /info` lists endpoints and version metadata.

## Machine-readable CLI

JSON goes to stdout; diagnostics and deprecation notices go to stderr.
Exit codes: `0` success, `1` failure, `2` usage error. Errors carry the fix:
removed/renamed flags exit 2 with the replacement spelled out, and an invalid
classifier selection lists the valid names.

| Command | What you get |
|---------|--------------|
| `merve validate --json` | Config validity + per-check results |
| `merve list-classifiers --json` | Classifier names + default |
| `merve tag --status --json` | Per-classifier version/tag status |
| `merve version --json --detailed` | Classifier + tool versions |
| `merve images --json` | Built container images |
| `merve status --json` | Docker/config/environment status |
| `merve doctor --json` | Full diagnosis with fix suggestions |
| `merve schema` | JSON Schema for `mlserver.yaml` |

## Workflow: change → release → deploy

1. Edit the predictor/artifacts; check with `merve validate` and `merve serve`.
2. Commit, then tag the release: `merve tag <patch|minor|major> --classifier <name>`
   — this writes `<name>/vX.Y.Z`; the released version comes ONLY from this tag.
3. `git push --tags` → the GitHub Actions workflow
   (`.github/workflows/ml-classifier-container-build.yml`) builds and publishes
   the container.
4. Manual container ops: `merve build`, `merve push --classifier <name>
   --registry <url>`, `merve run --classifier <name>`, `merve images`, `merve clean`.

[MULTI]## Multi-classifier rules
[MULTI]
[MULTI]- ONE server process serves ONE classifier. Select at startup with
[MULTI]  `merve serve --classifier <name>` or the `MLSERVER_CLASSIFIER` env var
[MULTI]  (containers/Kubernetes). Precedence: `--classifier` flag >
[MULTI]  `MLSERVER_CLASSIFIER` > config `default_classifier`. An invalid value
[MULTI]  fails startup loudly, listing the valid names (fail-fast by design).
[MULTI]- `merve build` builds ONE commit image bundling every classifier
[MULTI]  (`<repo>:<git-sha>` + `<repo>:latest`, no baked classifier).
[MULTI]- `merve push --classifier X --registry <url>` applies release aliases
[MULTI]  (`<repo>:X-vN.N.N`, `<repo>:X-latest`) on that same image — no rebuild.
[MULTI]- Tag each classifier independently: `merve tag patch --classifier <name>`.

## Health and readiness

`GET /healthz` returns `200 {"status": "ok", "model": ...}` once the model is
loaded and `503 {"status": "loading", "model": null}` before that — point
liveness, readiness, and startup probes at it. `GET /status` exposes
concurrency-slot availability; overflow prediction requests get `503` with a
`Retry-After` header.

## Do / Don't

- DO run `merve validate --json` after any config edit, `merve doctor --json`
  when something is broken.
- DO use top-level request keys; DON'T add the deprecated `payload` wrapper.
- DON'T hand-edit versions; versions come from `merve tag` git tags.
- DON'T rename `mlserver.yaml`, the `mlserver` module, or `MLSERVER_*` env vars.
- Full documentation: https://github.com/core64-lab/merve/tree/main/docs
"""


def generate_agents_md(
    classifier_names: list[str],
    default_classifier: Optional[str],
    multi: bool,
    mlserver_version: str,
) -> str:
    """Render the RFC 0002 §4 AGENTS.md template to a string.

    Args:
        classifier_names: Classifier names in the repo (for the multi listing).
        default_classifier: The default classifier; falls back to the first
            name in ``classifier_names`` when ``None``.
        multi: Select the multi-classifier variant when ``True``, otherwise the
            single-classifier variant.
        mlserver_version: Installed merve version, stamped into the header.

    Returns:
        The rendered Markdown, ending with exactly one trailing newline. The
        ``[SINGLE]``/``[MULTI]`` markers never appear in the output.
    """
    # ``{first_classifier}`` is not templated anywhere in the body; the first
    # classifier name only serves as the default fallback below.
    resolved_default = default_classifier or (classifier_names[0] if classifier_names else "")
    classifier_list = ", ".join(f"`{name}`" for name in classifier_names)

    rendered_lines: list[str] = []
    for line in _AGENTS_MD_TEMPLATE.split("\n"):
        if line.startswith("[SINGLE]"):
            if multi:
                continue
            line = line[len("[SINGLE]") :]
        elif line.startswith("[MULTI]"):
            if not multi:
                continue
            line = line[len("[MULTI]") :]
        rendered_lines.append(line)

    rendered = "\n".join(rendered_lines)
    rendered = (
        rendered.replace("{merve_version}", mlserver_version)
        .replace("{TEMPLATE_VERSION}", AGENTS_MD_TEMPLATE_VERSION)
        .replace("{classifier_list}", classifier_list)
        .replace("{default_classifier}", resolved_default)
    )

    # Guarantee exactly one trailing newline regardless of template edits.
    return rendered.rstrip("\n") + "\n"


def parse_agents_md_version(path: Path) -> Optional[str]:
    """Extract the template-version stamp from an AGENTS.md file.

    Reads the ``AGENTS.md template version: <X.Y>`` marker from the generated
    header comment.

    Args:
        path: Path to the AGENTS.md file.

    Returns:
        The version string (e.g. ``"1.0"``), or ``None`` when the file cannot
        be read or carries no parseable stamp.
    """
    try:
        content = Path(path).read_text(encoding="utf-8")
    except Exception:
        return None

    match = re.search(r"AGENTS\.md template version:\s*([\d.]+)", content)
    if match:
        return match.group(1)
    return None


def init_agents_md(
    project_path: str = ".", force: bool = False
) -> tuple[bool, str, dict[str, str]]:
    """Generate ``AGENTS.md`` for a classifier repo, detecting its config shape.

    Same return contract as ``init_github_actions``: ``(success, message,
    files_created)``. Detects single vs multi config from ``mlserver.yaml``;
    without a config, renders the single-classifier variant using the
    (sanitized) directory name as the classifier name. Never overwrites an
    existing file unless ``force`` is set.

    Args:
        project_path: Path to the classifier project.
        force: Overwrite an existing AGENTS.md.

    Returns:
        Tuple of (success, message, files_created).
    """
    from .container import _get_installed_mlserver_version
    from .init_project import sanitize_name
    from .multi_classifier import detect_multi_classifier_config, list_available_classifiers

    project_path = Path(project_path).resolve()

    if not project_path.is_dir():
        return False, f"Path does not exist or is not a directory: {project_path}", {}

    agents_md_path = project_path / "AGENTS.md"
    if agents_md_path.exists() and not force:
        return (
            True,
            "Skipped AGENTS.md (already exists). Use --force to overwrite.",
            {},
        )

    mlserver_yaml_path = project_path / "mlserver.yaml"

    multi = False
    default_classifier: Optional[str] = None

    if mlserver_yaml_path.exists() and detect_multi_classifier_config(str(mlserver_yaml_path)):
        # Multi-classifier repo: list the classifiers and read the raw default.
        multi = True
        classifier_names = list_available_classifiers(str(mlserver_yaml_path))
        default_classifier = _read_default_classifier(mlserver_yaml_path)
        n = len(classifier_names)
        message = f"Generated AGENTS.md (multi-classifier: {n} classifier{'s' if n != 1 else ''})."
    elif mlserver_yaml_path.exists():
        # Single-classifier repo: use classifier.name when present.
        classifier_name = _read_single_classifier_name(mlserver_yaml_path) or sanitize_name(
            project_path.name
        )
        classifier_names = [classifier_name]
        message = "Generated AGENTS.md (single-classifier)."
    else:
        # No config at all: single-classifier variant from the directory name.
        classifier_name = sanitize_name(project_path.name)
        classifier_names = [classifier_name]
        message = (
            "Generated AGENTS.md (single-classifier variant). "
            f"No mlserver.yaml found; used directory name '{classifier_name}'."
        )

    mlserver_version = _get_installed_mlserver_version() or "unknown"

    content = generate_agents_md(
        classifier_names=classifier_names,
        default_classifier=default_classifier,
        multi=multi,
        mlserver_version=mlserver_version,
    )

    with open(agents_md_path, "w") as f:
        f.write(content)

    return True, message, {"agents_md": "AGENTS.md"}


def _read_default_classifier(mlserver_yaml_path: Path) -> Optional[str]:
    """Read the ``default_classifier`` key from a multi-classifier config."""
    try:
        import yaml

        with open(mlserver_yaml_path) as f:
            config = yaml.safe_load(f)
        if isinstance(config, dict):
            default = config.get("default_classifier")
            if isinstance(default, str) and default.strip():
                return default
    except Exception:
        pass
    return None


def _read_single_classifier_name(mlserver_yaml_path: Path) -> Optional[str]:
    """Read ``classifier.name`` from a single-classifier config, if present."""
    try:
        import yaml

        with open(mlserver_yaml_path) as f:
            config = yaml.safe_load(f)
        if isinstance(config, dict):
            classifier = config.get("classifier")
            if isinstance(classifier, dict):
                name = classifier.get("name")
                if isinstance(name, str) and name.strip():
                    return name
    except Exception:
        pass
    return None
