"""Unit tests for AGENTS.md generation, `merve init-agents`, and the doctor check.

Covers RFC 0002 W-A1 (A1 + A2): the generated agent/operator guide scaffolded by
`merve init`, regenerated by `merve init-agents`, and checked for staleness by
`merve doctor`.
"""

from typer.testing import CliRunner

from mlserver.agents_md import (
    AGENTS_MD_TEMPLATE_VERSION,
    generate_agents_md,
    init_agents_md,
    parse_agents_md_version,
)
from mlserver.cli import app
from mlserver.doctor import CheckStatus, check_agents_md

runner = CliRunner()


class TestGenerateAgentsMdSingle:
    """Single-classifier variant rendering."""

    def _render(self):
        return generate_agents_md(
            classifier_names=["demo"],
            default_classifier=None,
            multi=False,
            mlserver_version="1.2.3",
        )

    def test_no_multi_content(self):
        content = self._render()
        assert "## Multi-classifier rules" not in content
        assert "MLSERVER_CLASSIFIER" not in content

    def test_serve_line_has_no_classifier_flag(self):
        content = self._render()
        assert "- Serve locally: `merve serve`" in content
        assert "merve serve --classifier" not in content

    def test_version_stamp_line(self):
        content = self._render()
        assert f"AGENTS.md template version: {AGENTS_MD_TEMPLATE_VERSION}" in content

    def test_stamps_merve_version(self):
        content = self._render()
        assert "Generated by merve 1.2.3" in content

    def test_do_not_edit_by_hand(self):
        content = self._render()
        assert "Do not edit by hand" in content

    def test_markers_absent_from_output(self):
        content = self._render()
        assert "[SINGLE]" not in content
        assert "[MULTI]" not in content

    def test_ends_with_single_newline(self):
        content = self._render()
        assert content.endswith("\n")
        assert not content.endswith("\n\n")

    def test_no_unrendered_placeholders(self):
        content = self._render()
        for placeholder in (
            "{merve_version}",
            "{TEMPLATE_VERSION}",
            "{classifier_list}",
            "{default_classifier}",
            "{first_classifier}",
        ):
            assert placeholder not in content

    def test_canonical_json_snippet_preserved(self):
        # The {...} JSON in the curl example must survive rendering untouched.
        content = self._render()
        assert '{"records": [{"feature_a": 1.0, "feature_b": "x"}]}' in content


class TestGenerateAgentsMdMulti:
    """Multi-classifier variant rendering."""

    def _render(self, default="b"):
        return generate_agents_md(
            classifier_names=["a", "b"],
            default_classifier=default,
            multi=True,
            mlserver_version="9.9.9",
        )

    def test_has_multi_section(self):
        content = self._render()
        assert "## Multi-classifier rules" in content

    def test_backticked_classifier_list(self):
        content = self._render()
        assert "`a`, `b`" in content

    def test_default_classifier_present(self):
        content = self._render()
        assert "Default: b." in content

    def test_default_falls_back_to_first(self):
        content = self._render(default=None)
        assert "Default: a." in content

    def test_mlserver_classifier_precedence_text(self):
        content = self._render()
        assert "MLSERVER_CLASSIFIER` > config `default_classifier`" in content

    def test_multi_serve_line(self):
        content = self._render()
        assert "- Serve locally: `merve serve --classifier <name>`" in content

    def test_markers_absent_from_output(self):
        content = self._render()
        assert "[SINGLE]" not in content
        assert "[MULTI]" not in content


class TestParseAgentsMdVersion:
    """parse_agents_md_version round-trip and edge cases."""

    def test_round_trip(self, tmp_path):
        content = generate_agents_md(["demo"], None, multi=False, mlserver_version="1.0.0")
        path = tmp_path / "AGENTS.md"
        path.write_text(content)
        assert parse_agents_md_version(path) == AGENTS_MD_TEMPLATE_VERSION

    def test_round_trip_multi(self, tmp_path):
        content = generate_agents_md(["a", "b"], "a", multi=True, mlserver_version="1.0.0")
        path = tmp_path / "AGENTS.md"
        path.write_text(content)
        assert parse_agents_md_version(path) == AGENTS_MD_TEMPLATE_VERSION

    def test_no_stamp_returns_none(self, tmp_path):
        path = tmp_path / "AGENTS.md"
        path.write_text("# Just a heading\n\nNo stamp here.\n")
        assert parse_agents_md_version(path) is None

    def test_missing_path_returns_none(self, tmp_path):
        assert parse_agents_md_version(tmp_path / "does_not_exist.md") is None


class TestInitAgentsMd:
    """init_agents_md config-shape detection and skip/force semantics."""

    def test_creates_file(self, tmp_path):
        success, message, files = init_agents_md(str(tmp_path))
        assert success is True
        assert files == {"agents_md": "AGENTS.md"}
        assert (tmp_path / "AGENTS.md").exists()

    def test_skips_without_force(self, tmp_path):
        init_agents_md(str(tmp_path))
        (tmp_path / "AGENTS.md").write_text("sentinel content\n")

        success, message, files = init_agents_md(str(tmp_path))
        assert success is True
        assert files == {}
        assert "already exists" in message
        # File was not overwritten.
        assert (tmp_path / "AGENTS.md").read_text() == "sentinel content\n"

    def test_overwrites_with_force(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text("sentinel content\n")

        success, message, files = init_agents_md(str(tmp_path), force=True)
        assert success is True
        assert files == {"agents_md": "AGENTS.md"}
        content = (tmp_path / "AGENTS.md").read_text()
        assert content != "sentinel content\n"
        assert "Operating this repository" in content

    def test_invalid_path(self, tmp_path):
        success, message, files = init_agents_md(str(tmp_path / "nope" / "missing"))
        assert success is False
        assert files == {}
        assert "not a directory" in message or "does not exist" in message

    def test_multi_classifier_detection(self, tmp_path):
        (tmp_path / "mlserver.yaml").write_text(
            "classifiers:\n"
            "  sentiment:\n"
            "    predictor:\n"
            "      module: sentiment_predictor\n"
            "      class_name: SentimentPredictor\n"
            "  fraud:\n"
            "    predictor:\n"
            "      module: fraud_predictor\n"
            "      class_name: FraudPredictor\n"
            "default_classifier: fraud\n"
        )

        success, message, files = init_agents_md(str(tmp_path))
        assert success is True
        content = (tmp_path / "AGENTS.md").read_text()
        assert "## Multi-classifier rules" in content
        assert "`sentiment`, `fraud`" in content
        assert "Default: fraud." in content

    def test_single_classifier_uses_config_name(self, tmp_path):
        (tmp_path / "mlserver.yaml").write_text(
            "predictor:\n  module: p\n  class_name: P\n"
            "classifier:\n  name: my-classifier\n  version: '1.0.0'\n"
        )

        success, message, files = init_agents_md(str(tmp_path))
        assert success is True
        content = (tmp_path / "AGENTS.md").read_text()
        assert "## Multi-classifier rules" not in content
        assert "single-classifier" in message

    def test_no_config_uses_directory_name(self, tmp_path):
        project_dir = tmp_path / "my-model-repo"
        project_dir.mkdir()

        success, message, files = init_agents_md(str(project_dir))
        assert success is True
        # No mlserver.yaml -> single variant generated, message says so.
        assert "No mlserver.yaml" in message
        assert "my_model_repo" in message  # sanitized directory name
        content = (project_dir / "AGENTS.md").read_text()
        assert "## Multi-classifier rules" not in content


class TestInitAgentsCli:
    """CliRunner tests for `merve init-agents`."""

    def test_creates_in_tmp_project(self, tmp_path):
        result = runner.invoke(app, ["init-agents", "-C", str(tmp_path)])
        assert result.exit_code == 0, result.output
        assert (tmp_path / "AGENTS.md").exists()

    def test_rerun_reports_already_exists(self, tmp_path):
        first = runner.invoke(app, ["init-agents", "-C", str(tmp_path)])
        assert first.exit_code == 0, first.output

        second = runner.invoke(app, ["init-agents", "-C", str(tmp_path)])
        assert second.exit_code == 0, second.output
        assert "already exists" in second.output

    def test_force_overwrites(self, tmp_path):
        runner.invoke(app, ["init-agents", "-C", str(tmp_path)])
        (tmp_path / "AGENTS.md").write_text("sentinel\n")

        result = runner.invoke(app, ["init-agents", "-C", str(tmp_path), "--force"])
        assert result.exit_code == 0, result.output
        content = (tmp_path / "AGENTS.md").read_text()
        assert content != "sentinel\n"
        assert "Operating this repository" in content

    def test_legacy_p_rejected_with_pointer(self, tmp_path):
        result = runner.invoke(app, ["init-agents", "-p", str(tmp_path)])
        assert result.exit_code == 2
        # Error points at the replacement flag (RFC 0001 D8).
        assert "-C" in result.output
        assert "--path" in result.output


class TestInitCreatesAgentsMd:
    """`merve init` scaffolds AGENTS.md alongside mlserver.yaml."""

    def test_init_creates_agents_md(self, tmp_path):
        result = runner.invoke(
            app, ["init", "--classifier", "demo", "--no-github", "-C", str(tmp_path)]
        )
        assert result.exit_code == 0, result.output

        agents_md = tmp_path / "AGENTS.md"
        assert agents_md.exists()
        assert (tmp_path / "mlserver.yaml").exists()

        content = agents_md.read_text()
        assert f"AGENTS.md template version: {AGENTS_MD_TEMPLATE_VERSION}" in content
        assert "[SINGLE]" not in content
        assert "[MULTI]" not in content


class TestCheckAgentsMd:
    """The doctor AGENTS.md check across its three states (never FAILED)."""

    def test_missing_is_skipped(self, tmp_path):
        result = check_agents_md(str(tmp_path))
        assert result.name == "AGENTS.md"
        assert result.status == CheckStatus.SKIPPED
        assert "init-agents" in result.suggestion

    def test_stale_stamp_is_warning(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text(
            "<!-- Generated by merve x.y.z. Do not edit by hand;\n"
            "     AGENTS.md template version: 0.9 -->\n\n# Old guide\n"
        )
        result = check_agents_md(str(tmp_path))
        assert result.name == "AGENTS.md"
        assert result.status == CheckStatus.WARNING
        assert "0.9" in result.message
        assert "init-agents" in result.suggestion

    def test_unstamped_is_warning(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text("# Hand-written guide, no stamp\n")
        result = check_agents_md(str(tmp_path))
        assert result.status == CheckStatus.WARNING
        assert "no template version stamp" in result.message

    def test_current_stamp_passes(self, tmp_path):
        content = generate_agents_md(["demo"], None, multi=False, mlserver_version="1.0.0")
        (tmp_path / "AGENTS.md").write_text(content)
        result = check_agents_md(str(tmp_path))
        assert result.status == CheckStatus.PASSED
        assert AGENTS_MD_TEMPLATE_VERSION in result.message

    def test_never_failed(self, tmp_path):
        # Advisory only (RFC 0002 A2): none of the states may be FAILED.
        missing = check_agents_md(str(tmp_path))
        (tmp_path / "AGENTS.md").write_text("no stamp\n")
        unstamped = check_agents_md(str(tmp_path))
        for result in (missing, unstamped):
            assert result.status != CheckStatus.FAILED
